var ALIASES = {};
ALIASES["proc_macro2"] = {};
ALIASES["quote"] = {};
ALIASES["syn"] = {};
ALIASES["thiserror"] = {};
ALIASES["thiserror_impl"] = {};
ALIASES["unicode_xid"] = {};
ALIASES["xml"] = {};
ALIASES["xsd"] = {};
